---
title: "Project 1 Team 8"
# date: "today"
#date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  #pdf_document:
    #toc: yes
    #toc_depth: '3'
---

```{r init, include=F}
library(ezids)
```


```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, results = "markup", message = F)
# knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. 
```

```{r}
p<-read.csv("D:\\Dataset1.csv")
str(p)
summary(p)
p$ethnicity<-as.factor(p$ethnicity)
p$gender<-as.factor(p$gender)
p$gender<-as.factor(p$icu_type)
summary(p)

p <- p[, !names(p) %in% c('bilirubin_apache')]
p <- p[, !names(p) %in% c('creatinine_apache')]
p <- p[, !names(p) %in% c('glucose_apache')]
summary(p)
```

```{r}
p[p == ''] <- NA
s=na.omit(p)
summary(p)
s[1:10,]
summary(s)
nrow(s)
```

```{r}
c <- s$heart_rate_apache

q1 <- quantile(c, 0.25)
q3 <- quantile(c, 0.75)

iqr_value <- IQR(c)

lower_bound <- q1 - 1.5 * iqr_value
upper_bound <- q3 + 1.5 * iqr_value


outliers <- c < lower_bound | c > upper_bound


print("Outliers:")
print(c[outliers])

print("Lower Bound:")
print(lower_bound)
print("Upper Bound:")
print(upper_bound)

cleaned_data <- s[!(s$heart_rate_apache %in% outliers$heart_rate_apache),]
nrow(cleaned_data)

```

```{r}
library(ggplot2)
ggplot(data.frame(x=cleaned_data$heart_rate_apache), aes(x))+geom_histogram(binwidth = 2, color="black",fill="blue")+labs(title="visualization of heart rate without outliers")

ggplot(data.frame(x=cleaned_data$bmi), aes(x))+geom_histogram(binwidth = 2, color="black",fill="blue")+labs(title="visualization of bmi with outliers")
```

```{r}
c3 <- cleaned_data$bmi


q1bmi <- quantile(c3, 0.25)
q3bmi <- quantile(c3, 0.75)


iqr_valuebmi <- IQR(c3)


lower_boundbmi <- q1bmi - 1.5 * iqr_valuebmi
upper_boundbmi <- q3bmi + 1.5 * iqr_valuebmi


outliersbmi <- cleaned_data[c3 < lower_boundbmi | c3 > upper_boundbmi, ]


print("Outliers:")
print(outliersbmi)


print("Lower Bound:")
print(lower_boundbmi)
print("Upper Bound:")
print(upper_boundbmi)




cleaned_data3 <-cleaned_data[!(cleaned_data$bmi %in% outliersbmi$bmi),]
#nrow(s)
nrow(cleaned_data3)

```

```{r}
c4 <- cleaned_data3$age


q1age <- quantile(c4, 0.25)
q3age <- quantile(c4, 0.75)


iqr_valueage <- IQR(c4)


lower_boundage <- q1age - 1.5 * iqr_valueage
upper_boundage <- q3age + 1.5 * iqr_valueage


outliersage <- cleaned_data3[c4 < lower_boundage | c4 > upper_boundage, ]


print("Outliers:")
print(outliersage)


print("Lower Bound:")
print(lower_boundage)
print("Upper Bound:")
print(upper_boundage)




cleaned_data4 <-cleaned_data3[!(cleaned_data3$age %in% outliersage$age),]
#nrow(s)
nrow(cleaned_data4)

```

```{r}
library(caret)
encoding <- dummyVars("~ .", data = cleaned_data4)
encoded_data <- predict(encoded_data_model, newdata = cleaned_data4)
#print(encoded_data)
summary(encoded_data)
str(encoded_data)
m=as.data.frame(encoded_data)
#print(m)
str(m)
```

```{r}
install.packages("e1071")
library(e1071)

skew_before <- skewness(m$bmi)
print(skew_before)
#Log transformation
transformed_data <- log(m$bmi + 1)  
print(skewness(transformed_data))
m$bmi<-transformed_data
```

```{r}
#ggplot(data.frame(x=m$age), aes(x))+geom_histogram(binwidth = 0.002, #color="black",fill="blue")+labs(title="visualization of age without outliers before transformation")

#skew_before1 <- skewness(m$age)
#print(skew_before1)
#transformed_data1 <- log(m$age + 1)  


#skew_after1 <- skewness(transformed_data1)
#print(skew_after1)
#str(transformed_data1)
#cleaned_data4$age<-transformed_data1

#ggplot(data.frame(x=m$age), aes(x))+geom_histogram(binwidth = 0.002, #color="black",fill="blue")+labs(title="visualization of age without outliers after transformation")



#a<-exp(m$age)
#print(a)
```